### ISSUE TITLE
Improve .pre-commit-config by switching to external repos and consolidating

### ISSUE THREAD

**Issue by HarrisonWilde** [nestauk/ds-cookiecutter#193]
In general, it is better practice to minimise project dependencies and instead refer to "external" repos in .pre-commit-config e.g.:

```yaml
repos:
  - repo: local
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system
```

Should be:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
```

We can then automate a workflow to keep these hooks up to date, something like https://gitlab.com/vojko.pribudic.foss/pre-commit-update/ or https://github.com/floatingpurr/sync_with_poetry if we end up on poetry.
